### ISSUE TITLE
Widget to show tracking data

### ISSUE THREAD

**Issue by poi33** [bouvet-apps/app-matomo#4]
Request to add a [enonic widget](https://developer.enonic.com/docs/xp/stable/admin/widgets) that shows some statistics about the users site/page? 

Some statistics that would be useful to see:
* Number of unique visitors
* Number of views on this page
* Total time spent on this page, in seconds

Having this for a day, week, month and year would give quick access to the data. 

Could the [reporting api ](https://developer.matomo.org/api-reference/reporting-api#api-response-metric-definitions) be used to create this?

**Comment by matsovevada** [comment]
I'll make a task for this @poi33 and we'll see what we could do. Thank you for the suggestion!

**Comment by vi-h** [comment]
As far as I can tell, this was solved in https://github.com/bouvet-apps/app-matomo/pull/9/files 😊
